## YAML Template.
---
language: php
php:
  - 5.5
  - hhvm
  - 5.6
  
install:
    - composer install
    
before_script:
    - ./vendor/bin/phing createUnitDBUser
    - ./vendor/bin/phing createUnitDB
    - ./vendor/bin/phing migrateDevelopment
    
script:
    - ./vendor/bin/phpunit

matrix:
  allow_failures:
    - php: 5.6
 
notifications:
    email:
        - evought@pobox.com
