## YAML Template.
---
language: php
php:
  - hhvm
  - 5.6
  - 7.0
  
install:
    - composer install
    
before_script:
    - ./vendor/bin/phing createUnitDBUser
    - ./vendor/bin/phing createUnitDB
    - ./vendor/bin/phing migrateDevelopment
    
script:
    - ./vendor/bin/phpunit

matrix:
  allow_failures:
 
notifications:
    email:
        - evought@pobox.com
